# Generated by Django 4.0.4 on 2022-06-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
